### PR TITLE
Do not account for empty route costs in cost computations

### LINKED ISSUE #853: Performance degradation v0.11 involving vehicle types with different start and end depots
Hello!

Thanks for this awesome package.

It took several hours to understand that it wasn't my data instances that had changed enough, but that I had updated pyvrp to 0.11.2 while playing with my (other) dependencies.

I have a couple of instances I'm testing:

* small: 30 depots, 117 clients, 31 vehicles = 31 vehicle types
* large: 136 depots, 765 clients, 208 vehicles = 208 vehicle types

In version 0.10.1, pyvrp found initial feasible solutions in seconds (1s for the small, 40s for the large). and in less then 500 iterations for both.

In version 0.11.2, after 20 min it stops without having found any feasible solution in either instance. And it shows warnings of reaching scaling limits on objective function penalties.

For now, I pinned the 0.10.1 version. But if you care about these performance regressions and need some test cases to play, I can try to export the datasets. What is the easiest way to export them?

Franco

### PR DESCRIPTION
**Pull request by leonlan**
This PR fixes a bug identified in #853 by changing `Proposal` and `costEvaluator.deltaCost` to evaluate empty routes as having no cost.

Empty routes can have costs, specifically when their associated vehicle type has different start and end depots with non-zero distance/duration between. It is then also possible to have excess distance and time warp if the vehicle type has maximum route distance or duration constraints.

Having empty routes with costs caused a strange situation when computing delta costs with the instances provided in #853. If an empty route already had some time warp, then inserting a client could reduce its time warp, while the new route still had some time warp. The search would continuously insert clients in empty routes because the delta cost showed to be improving. However, this introduced new routes in the solution with time warp, whereas the empty routes were actually not part of the solution.

The proposed fix is to special-case `Proposal` and `costEvaluator.deltaCost` to assume zero cost whenever a route (proposal) is empty. This also corresponds with how we handle empty routes: we don't allow empty routes to be part of a solution, i.e., they don't contribute to a solution's cost.

I also double-checked that the instances from #853 can be solved feasibly after this change.

- [x] Closes #853.
- [ ] Adds and passes relevant tests.
- [ ] Has well-formatted code and documentation.

<details>

**Notes**:

Please read our [contributing guidelines](https://pyvrp.org/dev/contributing.html) first.
In particular:

- You must add tests when making code changes.
  This keeps the code coverage level up, and helps ensure the changes work as intended.
- When fixing a bug, you must add a test that would produce the bug in the master branch, and then show that it is fixed with the new code. 
- New code additions must be well formatted. Changes should pass the pre-commit workflow, which you can set up locally using [pre-commit](https://pre-commit.com/#intro). 
- Docstring additions must render correctly, including escapes and LaTeX.
- Finally, it is essential that all contributions in this PR are license-compatible with PyVRP's MIT license.
  Please check that this PR can be included into PyVRP under the MIT license.

</details>

### CODE REVIEW

File: pyvrp/cpp/CostEvaluator.h
Comment (N-Wouda) [inline pyvrp/cpp/CostEvaluator.h:1]: Should we also update `CostEvaluator::penalisedCost`?

File: pyvrp/cpp/search/Route.h [hunk 1]
```diff
@@ -953,6 +966,12 @@ Route::Proposal<Segments...>::Proposal(Segments &&...segments)
     assert(last.last() == route->endDepot());      // must end at route end
 }
 
+template <Segment... Segments> bool Route::Proposal<Segments...>::empty() const
+{
+    auto const size = std::apply(
+        [](auto &&...args) { return (args.size() + ...); }, segments_);
```
Comment (N-Wouda) [inline pyvrp/cpp/search/Route.h]: Maybe split this off into a `Proposal::size()` member? And then check here that `size() == 2`?

File: pyvrp/cpp/search/Route.h [hunk 2]
```diff
@@ -953,6 +966,12 @@ Route::Proposal<Segments...>::Proposal(Segments &&...segments)
...
+    return size == 2;  // only contains start and end depot
+}
 template <Segment... Segments>
```
Comment (N-Wouda) [inline pyvrp/cpp/search/Route.h]:
```suggestion
}

template <Segment... Segments>
```

File: pyvrp/cpp/CostEvaluator.h [hunk 3]
```diff
@@ -256,14 +256,17 @@ bool CostEvaluator::deltaCost(Cost &out, T<Args...> const &proposal) const
 {
     auto const *route = proposal.route();
```
Comment (N-Wouda) [inline pyvrp/cpp/CostEvaluator.h]:
```suggestion
```
Maybe, nit, in line with the two-route deltaCost?

File: pyvrp/cpp/search/Route.cpp [hunk 4]
```diff
@@ -335,11 +335,12 @@ void Route::update()
...
 
         load_[dim] = 0;
-        excessLoad_[dim]
-            = loadBefore[dim][nodes.size() - 1].excessLoad(capacity);
         for (auto it = depots_.begin() + 1; it != depots_.end(); ++it)
             load_[dim] += loadBefore[dim][it->idx()].load();
 
+        excessLoad_[dim]
+            = loadBefore[dim][nodes.size() - 1].excessLoad(capacity);
+
```
Comment (N-Wouda) [inline pyvrp/cpp/search/Route.cpp]: Is this change required?

File: tests/search/test_Exchange.py [hunk 5]
```diff
@@ -625,3 +625,39 @@ def test_bug_release_time_shift_time_windows():
     op = Exchange10(data)
     cost_eval = CostEvaluator([], 1, 0)
     assert_equal(op.evaluate(route1[1], route2[0], cost_eval), 0)
+
+
+def test_empty_route_delta_cost_bug():
+    """
+    Fixes a bug identified in #853 where the empty route's costs are
+    incorrectly included in delta cost evaluations.
```
Comment (N-Wouda) [inline tests/search/test_Exchange.py]:
```suggestion
    Fixes a bug identified in #853 where the empty route's costs are
    incorrectly included in delta cost evaluations.
```
```suggestion
    Tests that a bug identified in #853 where the empty route's costs are
    incorrectly included in delta cost evaluations has been fixed.
```

File: tests/search/test_primitives.py [hunk 6]
```diff
@@ -80,7 +80,10 @@ def test_insert_cost_between_different_depots(ok_small_multi_depot):
     cost_eval = CostEvaluator([0], 0, 0)
     dist_mat = data.distance_matrix(0)
 
-    delta = dist_mat[0, 2] + dist_mat[2, 1] - dist_mat[0, 1]
+    # The delta cost is the distance from the start depot to the new node, and
+    # back to the end depot. The original route was empty so it should not
+    # contribute to the delta cost.
```
Comment (N-Wouda) [inline tests/search/test_primitives.py]:
```suggestion
    # back to the end depot. The route is currently empty so it does not
    # contribute to the delta cost.
```

File: tests/search/test_primitives.py [hunk 7]
```diff
@@ -262,3 +265,37 @@ def test_remove_consecutive_reload_depots(ok_small_multiple_trips):
 
     # And similarly removing the second depot should also be a no-op.
     assert_equal(remove_cost(route[4], data, CostEvaluator([1000], 0, 0)), 0)
+
+
+def test_empty_route_delta_cost_bug():
+    """
+    Fixes a bug identified in #853 where inserting or removing a client
+    involving an empty route incorrectly included the empty route's costs.
```
Comment (N-Wouda) [inline tests/search/test_primitives.py]: Same with "Tests that X has been fixed" - the test fixes nothing, but it does check that something has been done.

**Review by N-Wouda — COMMENTED** [review]
LGTM, but I think we should also update `CostEvaluator::penalisedCost`.

File: pyvrp/cpp/CostEvaluator.h [hunk 8]
```diff
@@ -225,6 +225,13 @@ Cost CostEvaluator::distPenalty(Distance distance, Distance maxDistance) const
...
+    if (arg.empty())
+    {
+        if constexpr (PrizeCostEvaluatable<T>)
+            return arg.uncollectedPrizes();
+        return 0;
+    }
+
     // Standard objective plus infeasibility-related penalty terms.
     auto const cost = arg.distanceCost() + arg.durationCost()
                       + (!arg.empty() ? arg.fixedVehicleCost() : 0)
```
Comment (N-Wouda) [inline pyvrp/cpp/CostEvaluator.h]:
```suggestion
                      + arg.fixedVehicleCost()
```
right?

Comment (leonlan) [reply pyvrp/cpp/CostEvaluator.h]: Right!

**Review by N-Wouda — APPROVED** [review]
